export const styles = {
    container: "bg-gray-50 dark:bg-gray-800 p-4 md:p-8 min-h-screen",
    title: "text-5xl md:text-6xl font-bold text-gray-900 dark:text-white mb-8 text-center",
    skeletonItem: "bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:p-12 animate-pulse",
    skeletonImage: "w-full h-48 md:h-64 bg-gray-300 dark:bg-gray-700 rounded-lg mb-4 flex items-center justify-center",
    skeletonImageText: "text-gray-200 dark:text-gray-600 text-xl font-semibold",
    skeletonLineLarge: "h-6 bg-gray-200 rounded-full dark:bg-gray-700 w-3/4 mb-2",
    skeletonLineMedium: "h-4 bg-gray-200 rounded-full dark:bg-gray-700 w-1/2 mb-4",
    skeletonLineSmall: "h-4 bg-gray-200 rounded-full dark:bg-gray-700 w-full mb-2",
    skeletonLineSmaller: "h-4 bg-gray-200 rounded-full dark:bg-gray-700 w-2/3 mb-2",
    skeletonContainer: "py-8 px-4 mx-auto max-w-screen-xl lg:py-16",
    skeletonGrid: "grid md:grid-cols-2 gap-8 md:max-w-3/4 mx-auto",
    errorModalContainer: "p-4 mb-4 text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800",
    errorModalHeader: "text-lg font-medium",
    errorModalBody: "mt-2 mb-4 text-sm",
    errorButton: "text-white bg-red-800 hover:bg-red-900 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-xs px-3 py-1.5 me-2 text-center inline-flex items-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800",
    errorDismissButton: "text-red-800 bg-transparent border border-red-800 hover:bg-red-900 hover:text-white focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-xs px-3 py-1.5 text-center dark:hover:bg-red-600 dark:border-red-600 dark:text-red-500 dark:hover:text-white dark:focus:ring-red-800",
    sectionContainer: "py-8 px-4 mx-auto max-w-screen-xl lg:py-16",
    sectionGrid: "grid md:grid-cols-2 gap-8 md:max-w-3/4 mx-auto",
    sectionItem: "bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-lg p-4 md:p-12",
    sectionImage: "w-full h-48 md:h-64 object-cover border-4 border-gray-600 dark:border-gray-300 rounded-lg shadow-lg mb-4",
    sectionTitle: "text-gray-900 dark:text-white text-xl md:text-3xl font-extrabold mb-2",
    sectionContent: "text-sm md:text-lg font-normal text-gray-500 dark:text-gray-400 mb-4",
};
